---

- name: IOS-XE - VRF configuration Playbook
  hosts: csr
  connection: local
  gather_facts: no

  #vars:
  #  provider:
  #    #  This references my "access.yml' file for login credentials
  #    # host: "{{ inventory_hostname }}"
  #    host: "{{ device_ip }}"
  #    username: "{{ access['username'] }}"
  #    password: "{{ access['password'] }}"

  tasks:

  - name: Get Login credentials
    # include_vars: /mnt/hgfs/vm_shared/ansible/access.yml
    #include_vars: /Users/crhill/vm_shared/ansible/projects/macsec_proj/access.yml
    include_vars: /mnt/hgfs/vm_shared/ansible/projects/macsec_proj/access.yml

  - name: Define Provider
    set_fact:
      provider:
      #  This references my "access.yml' file for login credentials
        host: "{{ inventory_hostname }}"
        # host: "{{ device_ip }}"
        username: "{{ access['username'] }}"
        password: "{{ access['password'] }}"

#  I used variables for all of the needed commands, offering flexibility for the operator

  - name: Create Key Chain Name & Key ID
    ios_config:
      src: DELETE-key-chain_1.j2
      provider: "{{ provider }}"
    notify:
      - write config

#  - name: Create Key Chain Name & Key ID
#    ios_config:
#      src: key-chain_name_ID.j2
#      provider: "{{ provider }}"
#    notify:
#      - write config
#
#  - name: Create Key String Number (aes-128)
#    ios_config:
#      src: key-chain_STRING_Num.j2
#      provider: "{{ provider }}"
#    notify:
#      - write config
#
#  - name: Create Key Lifetime
#    ios_config:
#      src: key-chain_lifetime.j2
#      provider: "{{ provider }}"
#    notify:
#      - write config


  handlers:
    - name: write config
      ios_command:
        commands: write memory
        provider: "{{ provider }}"
