---

- name: IOS-XE - VRF configuration Playbook
  hosts: csr
  connection: local
  gather_facts: no

  tasks:

  - name: Get Login credentials
    include_vars: /mnt/hgfs/vm_shared/ansible/projects/macsec_proj/access.yml

  - name: Define Provider
    set_fact:
      provider:
      #  This references my "access.yml' file for login credentials
        host: "{{ inventory_hostname }}"
        # host: "{{ device_ip }}"
        username: "{{ access['username'] }}"
        password: "{{ access['password'] }}"


  - name: Delete Entire Key Chain Name & Contents
    ios_config:
      src: DELETE-key-chain_1.j2
      provider: "{{ provider }}"
    notify:
      - write config

  handlers:
    - name: write config
      ios_command:
        commands: write memory
        provider: "{{ provider }}"
